### ISSUE TITLE
Bug: milestone planning report - API timeout

### ISSUE THREAD

**Issue by Laurac92** [pete-mc/Summit#48] opened 2024-01-04 23:26 UTC
**Describe the bug**
Unable to produce milestone planning report

**To Reproduce**

**Expected behavior**

**Screenshots**

![Screenshot_20240105_101633_Terrain  Summit](https://github.com/pete-mc/Summit/assets/155690520/10e0b2db-b21c-4b57-abb9-6ad619dcc242)

- Device : Samsung A51
 - OS: Android
 - App Type [e.g. chrome, edge, mobile app]
 - Version [e.g. 2.2.2]

**Additional context**

**Comment by AceLeader2023** [comment] 2024-01-06 05:11
Not able to reproduce the described issue based on the limited information provided.

Device: Samsung S22 Ultra
OS: Android
App Type: Mobile app
Version: V2.3.0

**Comment by pete-mc** [comment] 2024-01-09 02:55
This is an intermittent issue that relates to the Terrain API, I am aware of this and am working on a solution. It can also happen in the chrome/edge versions.

**Comment by pete-mc** [comment] 2024-01-16 09:08
Triple up button part is sorted in the latest release. The API issue will be solved as part of V3 which will integrate summit and terrain much more closely to reduce these sorts of issues.

**Comment by pete-mc** [comment] 2024-03-21 01:14
This is fixed in the new V3 version.

**Closed by pete-mc** 2024-03-21 01:14 UTC
Labels: bug, good first issue, v3.0.0 Development, Completed - Awaiting release
