### ISSUE TITLE
Bug: Title Incorrect

### ISSUE THREAD

**Issue by AceLeader2023** [pete-mc/Summit#44] opened 2024-01-01 20:12 UTC
**Describe the bug**
The title on the Record Badge Presentation report has an incorrect in that the Unit name is repeated 3 times. 

**To Reproduce**
1. Go to Present Awards

**Expected behavior**
It should say "Record Badge Presentation - [Unit Name]

**Screenshots**
![SmartSelect_20240102_065832_Terrain  Summit.jpg](https://github.com/pete-mc/Summit/assets/110509017/b2356d24-b229-4657-9243-30469217fcec)

**Device/ Version Deatils**
- Samsung S22 Ultra - Android 
- Mobile App
- 2.3.0

**Additional context**
The correct title is on the chrome version

**Comment by CrispyCamper** [comment] 2024-01-02 01:39
Can confirm

**Comment by pete-mc** [comment] 2024-01-06 14:55
Yeah, the issue with the buttons and header all appearing 3 times is the same root cause. It seems like on mobile terrain reloads part of the page 3 time so part of my code runs causing a triple up. I will merge these issues. Thanks for letting me know.

**Comment by pete-mc** [comment] 2024-01-09 02:57
@CrispyCamper can you check if this still happens on the 2.5.0 which should be coming out on the store any day now? Just waiting on google checks.

**Comment by pete-mc** [comment] 2024-01-09 12:42
Fixed with change from Cordova to Flutter in 2.4.2 releasing now.

**Closed** 2024-01-09 12:45 UTC
Labels: bug

**Comment by AceLeader2023** [comment] 2024-01-17 11:07
Issue has come back up in version 2.4.4 as per app but 2.4.6 as per the google play store. 

![Screenshot_20240117_220237.jpg](https://github.com/pete-mc/Summit/assets/110509017/36963410-b273-4938-a53a-a3f7056bd147)

**Details**
Samsung s22 ultra
