### ISSUE TITLE
Error loading members.

### ISSUE THREAD

**Issue by ozMerv** [pete-mc/Summit#93] opened 2024-02-05 03:18 UTC
All Reports  ( NOT Relaed to TOPO ) Report the same error.

Extention Version : 2.5.2
Chrome Version : Version 121.0.6167.140

**To Reproduce**
1. Install Extention
2. Click on Green Sumit Terrian and bottom of Menu
3. Click on Reports
4. Choose Milestone, OAS or  Peak Report

Error notification:
"Error loading members. Please click the button to try again. This is a Summit error. Please do not contact Terrain support for this issue. If this error persists please add an issue to the Summit GitHub repository."

**Comment by Bilby-CSL** [comment] 2024-02-05 11:17
I'm having the exact same issue. I have attempted to use both Chrome and Edge. I am the leader of 4 units on Terrain (Venturers, Scouts, Cubs A and Cubs B). I have attempted to run reports for each of the sections and I get the same response for all. 
The Tools section works but not the Reports section.

**Comment by Bilby-CSL** [comment] 2024-02-05 11:31
Using the phone app, I had the same error for the Scout section but there were results for the Cub A unit.

**Comment by Bilby-CSL** [comment] 2024-02-05 11:50
![Capture](https://github.com/pete-mc/Summit/assets/159019189/2c755dbf-0268-46be-b17b-9a84944bed9f)
![Capture2](https://github.com/pete-mc/Summit/assets/159019189/866156ef-2760-4788-bf8c-1265207a0f29)
(Sorry for multiple comments)
I've been refreshing browser and page and trying multiple times. I now have Scouts opening on Edge (attached screenshot) but Cubs A (AKA Tuesday) is not opening in Edge (2nd attached screenshot). (I have the opposite result on the phone app.
Just wanted to point out that the issue is not consistent.

**Comment by pete-mc** [comment] 2024-02-06 04:00
The new version I am working on should have this fixed, in the meantime a work around is to go to the group life area and then go back to the report. Let me know if the work around works or if you are still having it.

**Comment by pete-mc** [comment] 2024-03-21 01:12
This is fixed in the new V3 version.

**Closed by pete-mc** 2024-03-21 01:12 UTC
Labels: bug, question, v3.0.0 Development, Completed - Awaiting release, Confirmation Required Post Release
