### ISSUE TITLE
Button style - Save to Calendar

### ISSUE THREAD

**Issue by AceLeader2023** [pete-mc/Summit#37] opened 2023-12-30 11:12 UTC
Hi Peter, 

Doing a great job. 

I've just noticed on both the Chrome version and the Android app that the style of the "save to calendar" button in programming is not consistent with the other buttons for Summit.

![SmartSelect_20231229_213739_Terrain  Summit](https://github.com/pete-mc/Summit/assets/110509017/5cab7c0b-f150-4130-b39d-9716a6df1df1)

Thanks again for all your hard work. 

Adam
2nd Eltham Sea Scouts

**Comment by pete-mc** [comment] 2023-12-30 12:16
Thanks, are you using the Android version too now? Was the install process ok?

Which version was this installed from? In 2.3.0 in Chrome seems to be ok and 2.2.0 is ok on Android. You can tell the version from the logo, the version number came in with 2.2.0 so if there is no version is it likely 2.1.0 or older. 

![image](https://github.com/pete-mc/Summit/assets/8443346/797cd91c-5af0-47b0-8146-b40ca66c7974)
![image](https://github.com/pete-mc/Summit/assets/8443346/45a36a98-a75f-4a00-989f-0d20a2925955)
![image](https://github.com/pete-mc/Summit/assets/8443346/ea17d17c-814c-4c5e-a141-26ff8bb830bf)

**Comment by AceLeader2023** [comment] 2023-12-30 12:21
Chrome = 2.3.0
Android = 2.2.0 
Both do not have the correct style, as I see above in your pics. 

Yes using the Android version now, too - the installation process was easy

**Comment by AceLeader2023** [comment] 2023-12-30 12:26
Here is a screenshot of the Android output.
![Screenshot_20231230_232346_Terrain  Summit](https://github.com/pete-mc/Summit/assets/110509017/f2b1870f-b40b-4997-bd2d-b713dc75df11)

_Note covered Activity ID_

**Comment by AceLeader2023** [comment] 2023-12-30 13:20
I have just created a new plan, and it has the correct styling when the plan has not been concluded on both Android and Chrome.

So the incorrect button style is when the plan has been concluded.

**Comment by pete-mc** [comment] 2023-12-31 04:00
Oh OK, I hadn't looked at a concluded plan, I can confirm the issue now. Thanks for the info.

**Comment by pete-mc** [comment] 2024-01-07 02:57
Fixed in V2.4.0, release pending.

**Closed** 2024-01-07 09:58 UTC
Labels: bug, Completed - Awaiting release
